proto:
	@protoc \
		--proto_path=protobuf "protobuf/api.proto" \
		--go_out=internal/genproto/api --go_opt=paths=source_relative \
		--go-grpc_out=internal/genproto/api --go-grpc_opt=paths=source_relative